export const portfolioProjects = [
  {
    id: 1,
    slug: 'treza-care-ecommerce',
    title: 'Treza Care - Ayurvedic E-commerce',
    category: 'E-commerce',
    client: 'Treza Care',
    year: '2025',
    thumbnail: 'https://images.unsplash.com/photo-1556742400-b5b7c3e60833?w=800&q=80',
    color: '#00F5A0',
    tags: ['Shopify', 'E-commerce', 'Ayurveda', 'UI/UX'],
    description: 'Complete Shopify store redesign for ayurvedic products with custom theme development.',
    challenge: 'The client needed a modern, conversion-optimized store that reflected their premium ayurvedic brand identity.',
    solution: 'We created a custom Shopify theme with advanced filtering, product recommendations, and seamless checkout experience.',
    results: [
      '150% increase in conversion rate',
      '200+ products organized',
      'Mobile-first responsive design',
      'Custom product page templates'
    ],
    images: [
      'https://images.unsplash.com/photo-1556742400-b5b7c3e60833?w=1200&q=80',
      'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&q=80',
      'https://images.unsplash.com/photo-1512428559087-560fa5ceab42?w=1200&q=80',
    ],
    testimonial: {
      text: 'Visam Solutions transformed our online presence. Sales increased by 150% in just 3 months!',
      author: 'Founder, Treza Care',
    },
    link: 'https://trezacare.com',
  },
  {
    id: 2,
    slug: 'pixipom-digital-agency',
    title: 'PIXIPOM - Digital Marketing Agency',
    category: 'Branding',
    client: 'PIXIPOM',
    year: '2024',
    thumbnail: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&q=80',
    color: '#8B5CF6',
    tags: ['Branding', 'Logo Design', 'Brand Identity'],
    description: 'Complete brand identity design for a digital marketing agency including logo, colors, and brand guidelines.',
    challenge: 'Create a modern, memorable brand identity that stands out in the competitive digital marketing space.',
    solution: 'Developed a vibrant, energetic brand with bold typography and gradient color palette.',
    results: [
      'Award-winning logo design',
      'Complete brand guidelines',
      '50+ branded materials',
      'Social media templates'
    ],
    images: [
      'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=1200&q=80',
      'https://images.unsplash.com/photo-1558655146-d09347e92766?w=1200&q=80',
      'https://images.unsplash.com/photo-1572044162444-ad60f128bdea?w=1200&q=80',
    ],
    testimonial: {
      text: 'The brand identity perfectly captures our energy and vision. Client inquiries increased by 200%!',
      author: 'CEO, PIXIPOM',
    },
    link: 'https://pixipom.com',
  },
  {
    id: 3,
    slug: 'sanan-group-corporate-website',
    title: 'Sanan Group - Corporate Website',
    category: 'Web Development',
    client: 'Sanan Group',
    year: '2025',
    thumbnail: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80',
    color: '#0EA5E9',
    tags: ['React', 'Corporate', 'CMS', 'Responsive'],
    description: 'Modern corporate website built with React and WordPress headless CMS.',
    challenge: 'Build a scalable, fast-loading corporate site with easy content management.',
    solution: 'Implemented React frontend with WordPress headless CMS backend for optimal performance.',
    results: [
      '90+ PageSpeed score',
      'Headless CMS integration',
      'Multi-language support',
      'Advanced SEO optimization'
    ],
    images: [
      'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&q=80',
      'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=1200&q=80',
      'https://images.unsplash.com/photo-1533750349088-cd871a92f312?w=1200&q=80',
    ],
    testimonial: {
      text: 'Professional, fast, and exactly what we needed. The CMS makes updates incredibly easy.',
      author: 'Marketing Head, Sanan Group',
    },
    link: 'https://sanangroup.com',
  },
  {
    id: 4,
    slug: 'premium-packaging-design',
    title: 'Premium Packaging Design Collection',
    category: 'Packaging',
    client: 'Multiple Brands',
    year: '2024',
    thumbnail: 'https://images.unsplash.com/photo-1612033448550-9d6f9c17f07c?w=800&q=80',
    color: '#F59E0B',
    tags: ['Packaging', 'Print Design', 'Product Design'],
    description: 'Premium packaging designs for FMCG and luxury product brands.',
    challenge: 'Create distinctive packaging that stands out on retail shelves.',
    solution: 'Developed unique packaging concepts with focus on shelf impact and brand storytelling.',
    results: [
      '20+ packaging designs',
      '100% client satisfaction',
      'Award-winning designs',
      'Increased shelf visibility'
    ],
    images: [
      'https://images.unsplash.com/photo-1612033448550-9d6f9c17f07c?w=1200&q=80',
      'https://images.unsplash.com/photo-1615873968403-89e068629265?w=1200&q=80',
      'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=1200&q=80',
    ],
    testimonial: {
      text: 'The packaging designs are stunning! Our products now have premium shelf presence.',
      author: 'Brand Manager',
    },
  },
  {
    id: 5,
    slug: 'social-media-branding-campaign',
    title: 'Social Media Branding Campaign',
    category: 'Marketing',
    client: 'Multiple Clients',
    year: '2025',
    thumbnail: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800&q=80',
    color: '#EC4899',
    tags: ['Social Media', 'Content Design', 'Marketing'],
    description: 'Complete social media branding and content strategy for multiple brands.',
    challenge: 'Create consistent, engaging social media presence that drives engagement.',
    solution: 'Developed comprehensive content calendars with custom templates and brand guidelines.',
    results: [
      '500+ social posts designed',
      '300% engagement increase',
      'Consistent brand presence',
      'Viral content created'
    ],
    images: [
      'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=1200&q=80',
      'https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=1200&q=80',
      'https://images.unsplash.com/photo-1611162618071-b39a2ec055fb?w=1200&q=80',
    ],
    testimonial: {
      text: 'Our social media engagement skyrocketed! The content is consistently amazing.',
      author: 'Social Media Manager',
    },
  },
  {
    id: 6,
    slug: 'restaurant-app-ui-ux',
    title: 'Restaurant Ordering App - UI/UX',
    category: 'App Design',
    client: 'Food Tech Startup',
    year: '2024',
    thumbnail: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&q=80',
    color: '#10B981',
    tags: ['Mobile App', 'UI/UX', 'Figma', 'Prototyping'],
    description: 'Complete mobile app design for restaurant ordering platform.',
    challenge: 'Design intuitive ordering experience for multiple restaurants.',
    solution: 'Created user-friendly interface with smart filtering and personalized recommendations.',
    results: [
      '50+ screens designed',
      'Interactive prototypes',
      '4.8/5 user rating',
      'Seamless checkout flow'
    ],
    images: [
      'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=1200&q=80',
      'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=1200&q=80',
      'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1200&q=80',
    ],
    testimonial: {
      text: 'The app design is beautiful and intuitive. Users love the ordering experience!',
      author: 'Founder, Food Tech Startup',
    },
  },
];
