export const serviceData = {
  'brand-identity': {
    id: 1,
    title: 'Brand Identity & Logo Design',
    tagline: 'Building memorable brands that stand out',
    color: '#00F5A0',
    hero: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=1200&q=80',
    description: 'We create distinctive brand identities that capture your essence and resonate with your target audience. From concept to execution, we craft visual languages that tell your story.',
    shortDescription: 'Premium logo systems, brand guidelines, and complete visual identity that makes your brand unforgettable.',
    features: [
      'Custom logo design with multiple concepts',
      'Complete brand guidelines document',
      'Color palette and typography system',
      'Business card and stationery design',
      'Social media branding kit',
      'Brand strategy consultation',
    ],
    process: [
      { title: 'Discovery', desc: 'Understanding your brand, values, and target audience' },
      { title: 'Research', desc: 'Market analysis and competitor research' },
      { title: 'Concepts', desc: '3-5 initial logo concepts for your review' },
      { title: 'Refinement', desc: 'Revisions based on your feedback' },
      { title: 'Delivery', desc: 'Final files in all formats + brand guidelines' },
    ],
    pricing: '₹15,000 - ₹50,000',
    duration: '2-3 weeks',
    deliverables: [
      'Logo files (AI, EPS, SVG, PNG, JPG)',
      'Brand guidelines PDF (30+ pages)',
      'Color codes (RGB, CMYK, HEX)',
      'Typography specifications',
      'Social media templates',
      'Email signature design',
    ],
  },
  'web-development': {
    id: 2,
    title: 'Custom Website Development',
    tagline: 'Fast, scalable, and beautiful websites',
    color: '#0EA5E9',
    hero: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&q=80',
    description: 'We build modern, responsive websites using the latest technologies. From simple landing pages to complex web applications, we deliver solutions that perform.',
    shortDescription: 'Lightning-fast websites built with React, WordPress, or PHP. Fully responsive and SEO-optimized.',
    features: [
      'React.js / Next.js development',
      'WordPress / Headless CMS',
      'Responsive mobile-first design',
      'SEO optimization',
      'Performance optimization (90+ PageSpeed)',
      'Analytics integration',
    ],
    process: [
      { title: 'Planning', desc: 'Requirements gathering and project roadmap' },
      { title: 'Design', desc: 'UI/UX design and prototyping in Figma' },
      { title: 'Development', desc: 'Clean, scalable code development' },
      { title: 'Testing', desc: 'Cross-browser and device testing' },
      { title: 'Launch', desc: 'Deployment and post-launch support' },
    ],
    pricing: '₹30,000 - ₹2,00,000',
    duration: '4-8 weeks',
    deliverables: [
      'Fully responsive website',
      'Source code access',
      'CMS training documentation',
      'SEO setup',
      '3 months free support',
      'Hosting setup assistance',
    ],
  },
  'ecommerce': {
    id: 3,
    title: 'E-commerce Solutions',
    tagline: 'Sell more with optimized online stores',
    color: '#10B981',
    hero: 'https://images.unsplash.com/photo-1556742400-b5b7c3e60833?w=1200&q=80',
    description: 'Launch your online store with our complete e-commerce solutions. We build conversion-optimized stores on Shopify, WooCommerce, and custom platforms.',
    shortDescription: 'High-converting Shopify and WooCommerce stores with payment gateway and inventory management.',
    features: [
      'Shopify / WooCommerce setup',
      'Custom theme development',
      'Payment gateway integration',
      'Inventory management',
      'Product recommendations',
      'Abandoned cart recovery',
    ],
    process: [
      { title: 'Store Setup', desc: 'Platform setup and configuration' },
      { title: 'Design', desc: 'Custom theme design for your brand' },
      { title: 'Product Setup', desc: 'Product uploads and categorization' },
      { title: 'Testing', desc: 'Checkout flow and payment testing' },
      { title: 'Launch', desc: 'Go live with marketing support' },
    ],
    pricing: '₹40,000 - ₹3,00,000',
    duration: '3-6 weeks',
    deliverables: [
      'Fully functional online store',
      'Mobile-optimized checkout',
      'Payment gateway setup',
      'Email marketing integration',
      'Analytics & conversion tracking',
      '6 months support',
    ],
  },
  'packaging-design': {
    id: 4,
    title: 'Premium Packaging Design',
    tagline: 'Stand out on the shelf',
    color: '#F59E0B',
    hero: 'https://images.unsplash.com/photo-1612033448550-9d6f9c17f07c?w=1200&q=80',
    description: 'Create packaging that sells. We design eye-catching packaging for FMCG, cosmetics, food & beverage, and luxury products.',
    shortDescription: 'Eye-catching packaging that stands out on shelves and drives sales. From concept to print-ready files.',
    features: [
      'Custom packaging design',
      'Dieline creation',
      'Print-ready artwork',
      'Material recommendations',
      'Mockup visualizations',
      'Production coordination',
    ],
    process: [
      { title: 'Brief', desc: 'Understanding product and market positioning' },
      { title: 'Concepts', desc: '2-3 packaging design concepts' },
      { title: 'Refinement', desc: 'Revisions and finalization' },
      { title: 'Artwork', desc: 'Print-ready files with dielines' },
      { title: 'Production', desc: 'Coordination with printing partners' },
    ],
    pricing: '₹20,000 - ₹1,00,000',
    duration: '2-4 weeks',
    deliverables: [
      'Print-ready artwork files',
      'Dieline specifications',
      '3D mockups',
      'Material recommendations',
      'Color specifications',
      'Printing vendor coordination',
    ],
  },
  'digital-marketing': {
    id: 5,
    title: 'Digital Marketing & Advertising',
    tagline: 'Grow your business online',
    color: '#EC4899',
    hero: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=1200&q=80',
    description: 'Drive traffic, generate leads, and increase sales with our data-driven digital marketing strategies across all platforms.',
    shortDescription: 'Digital and print advertising campaigns that drive results. Google Ads, Facebook Ads, and more.',
    features: [
      'Social media marketing',
      'Google Ads & Facebook Ads',
      'Content marketing strategy',
      'Email marketing campaigns',
      'Influencer marketing',
      'Analytics & reporting',
    ],
    process: [
      { title: 'Audit', desc: 'Current marketing analysis' },
      { title: 'Strategy', desc: 'Custom marketing roadmap' },
      { title: 'Execution', desc: 'Campaign creation and launch' },
      { title: 'Optimization', desc: 'Continuous A/B testing' },
      { title: 'Reporting', desc: 'Monthly performance reports' },
    ],
    pricing: '₹15,000/month - ₹1,00,000/month',
    duration: 'Ongoing',
    deliverables: [
      'Monthly marketing strategy',
      'Content calendar',
      'Ad creatives',
      'Campaign management',
      'Monthly analytics reports',
      'ROI tracking',
    ],
  },
  'business-consulting': {
    id: 6,
    title: 'Business Consulting',
    tagline: 'Strategic guidance for growth',
    color: '#8B5CF6',
    hero: 'https://images.unsplash.com/photo-1553877522-43269d4ea984?w=1200&q=80',
    description: 'Get expert advice on business strategy, market positioning, and digital transformation. We help businesses scale and optimize operations.',
    shortDescription: 'Expert guidance for startups and businesses on branding, marketing, and growth strategies.',
    features: [
      'Business strategy development',
      'Market research & analysis',
      'Competitor analysis',
      'Digital transformation roadmap',
      'Process optimization',
      'Growth strategy planning',
    ],
    process: [
      { title: 'Assessment', desc: 'Current business analysis' },
      { title: 'Research', desc: 'Market and competitor research' },
      { title: 'Strategy', desc: 'Custom growth strategy development' },
      { title: 'Implementation', desc: 'Action plan creation' },
      { title: 'Support', desc: 'Ongoing guidance and support' },
    ],
    pricing: '₹5,000 - ₹50,000 per session',
    duration: '1-4 weeks',
    deliverables: [
      'Business analysis report',
      'Market research document',
      'Strategic roadmap',
      'Action plan with timeline',
      'Follow-up consultation',
      'Implementation support',
    ],
  },
};
